### ISSUE TITLE
Improve documentation 

### ISSUE THREAD

**Issue by aminya** [aminya/project_options#62]
- [x] add a website for the documentation #198 
- [x] add instructions for making an executable #58 
- [x] add instructions for making a header-only library #58 
- [x] add instructions for making a normal library #58 
- [ ] add instructions for using doxygen-docs target
- [ ] add instructions for using sanitizers (especially on windows)
- [ ] adding more examples for using the options:
	- [ ] using PCH headers
	- [ ] using coverage
	- [ ] overriding compiler warnings, 
	- [ ] adding more warnings
	- [ ] removing certain warnings for certain targets
- [ ] documenting the individual functions (e.g. enable_doxygen) in case more control is needed
 - [ ] add documentation for cross-compilation

**Comment by abeimler** [comment]
Would be nice if we can use the github Wiki for some things.
_(Readme should really be an overview and link to the Wiki, IMHO)_

For example what each Option do and how to uses them...
What warnings gets enabled, link to best practices.
Use of static code analyzers, sanitizers, how to enable them and why it matters (link to best practices)

Section for some util functions like `run_vcpkg()`

Some more Examples, Docker and maybe some Pitfalls...

**Comment by aminya** [comment]
We can also have a dedicated website with documentation:
https://gitlab.com/Pro1/doxygen-cmake-sphinx
